language: ruby

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  # - jruby
  - ree

before_install: gem install bundler -v 1.11.2

script: "bundle exec rake spec"

notifications:
  # disabled: true
  email: false
  # email:
  #   recipients:
  #     - 
  #   on_success: change
  #   on_failure: always
